In [5]:
#导入numpy库
import numpy as np
#检查numpy版本
print(f"numpy的版本为:{np.__version__}")


"""
一.数组的概念:
数组是一系列相同数据类型元素的集合, 数组中的元素可以是任意类型, 包括整型、浮点型、字符串、布尔型等。

数组的维度:
一维数组: 只有一列, 如[1, 2, 3, 4, 5],以 0-D 数组作为其元素的数组称为一维数组或 1-D 数组

二维数组: 具有两个维度, 如[[1, 2, 3], [4, 5, 6]],以 0-D 数组作为其元素的数组称为一维数组或 1-D 数组
这些通常用于表示矩阵或二阶张量

三维数组: 具有三个维度, 如[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

"""

"""

二.描述数组:
在 NumPy 和其他类似数据结构中，行和列是用来描述多维数组（矩阵）的两个基本维度。
在数学和计算机科学中，二维数组通常被表示为矩阵，矩阵的元素通常被组织为行和列。

定义习惯：将元素在水平方向上的分组称为行，在垂直方向上的分组称为列。
这个定义帮助人们理解数据在数组中的结构和布局

总结:在 NumPy 中，行指的是每个子数组（或子列表），而列指的是在每个子数组中的元素。
使用这样的术语可以更清晰地表达二维数组的结构。

"""


#使用 numpy.array() 可以轻松地将列表或元组转换为 NumPy 数组。
#创建数组
arr=np.array([1,2,3,4,5])
print(f"数组a{arr}的类型为:{type(arr)}")

#使用元组tuple创建数组
b=np.array((1,2,3,4,5))
print(f"数组b{b}的类型为:{type(b)}")

#高维数组,可以有任意数量的维度
#创建数组后，您可以使用 参数。ndmin关键字指定数组的最小维度。

c=np.array([1,2,3,4],ndmin=3)
print(f"数组c:{c},维度为:{c.ndim}")



numpy的版本为:2.2.1
数组a[1 2 3 4 5]的类型为:<class 'numpy.ndarray'>
数组b[1 2 3 4 5]的类型为:<class 'numpy.ndarray'>
数组c:[[[1 2 3 4]]],维度为:3


In [8]:
#还有其他创建数组的方式:np.zeros(),np.ones(),np.empty(),full(),  其中like形式都是根据数组形状
#eye.identify

import numpy as np


#zeros_like()根据给定的数组形状来填满0
print(np.zeros_like((3,3,3,3,3,3,3)))

#zeros()根据给定的形状来填0
np.zeros((3,3,3))

#同理ones()和ones_like()

[0 0 0 0 0 0 0]


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [11]:
import numpy as np

np.ones(10)
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
import numpy as np

#创建一个空的数组:

print(np.empty((2,3,4)))

print(np.empty_like((2,3,4)))
#其中里面都是垃圾值,填充才有意义

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[2 3 4]


In [ ]:
#numpy处理数组的能力更快:

import numpy as np

my_arr=np.array(range(100_0000))

list_data=[range(100_0000)]

#二者乘以2给每一个元素消耗的时间:

# 测量 numpy 数组操作的时间
%timeit my_arr * 2

# 测量 Python 列表操作的时间
%timeit [x * 2 for x in list_data]