In [ ]:
#numpy的数据类型(dtype):
#i-整数
#S-字符串
#b-布尔
#u-无符号整数
#f-浮
#c- 复杂浮点数
#m- 时间增量
#M- 日期时间
#O-对象
#U- Unicode 字符串
#V- 修复了其他类型的内存块 （ void ）


#"S" vs "U

#"S"	固定长度字节字符串	bytes	b'1'
#"U"	Unicode字符串	str	'1'

#为什么默认是字节字符串？
#NumPy的"S"类型设计初衷是用于存储二进制数据（如文件中的原始字节），而"U"类型更适用于文本处理场景。

In [3]:
#检查数组的数据类型
import numpy as np

arr = np.array([1, 2, 3, 4])

#arr.dtype方法:它返回数组的数据类型
print(arr.dtype)

int64


In [4]:
#获取包含字符串的数组的数据类型：
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [6]:
#创建具有已定义数据类型的数组
#该函数可以采用一个可选参数：它允许我们定义数组元素的预期数据类型：array(数组,dtype=)

import numpy as np

npy=np.array([1,2,3,4],dtype="S")

print(f"npy的数据类型为:{npy.dtype}")

npy的数据类型为:|S1


In [8]:
#我们也可以定义大小。i u f S U
#创建一个数据类型为 4 字节整数的数组

import numpy as np

npy=np.array([1,2,3,4],dtype="i4")

print(f"npy:{npy}的数据类型为:{npy.dtype}")

#注释:1字节等于8bit

npy:[1 2 3 4]的数据类型为:int32


In [1]:
#像 'a' 这样的非整数字符串不能转换为整数（会引发错误)

import numpy as np

arr = np.array(['a', '2', '3'], dtype='i8')

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
#转换现有数组的数据类型
#该函数会创建 数组，并允许您将数据类型指定为参数。arr.astype("参数")
import numpy as np

npy_int=np.array([1,2,3,4],dtype="i4")

print(f"npy_int:{npy_int}的数据类型为:{npy_int.dtype}")

#转为字节字符串
npy_str=npy_int.astype("S")

print(f"npy_str:{npy_str}数据类型为:{npy_str.dtype}")

#转为布尔类型
npy_bool=npy_int.astype(bool)

print(f"npy_bool:{npy_bool},数据类型:{npy_bool.dtype}")

#注释:在NumPy中，将整数数组转换为布尔类型时，非零值会被视为True


npy_int:[1 2 3 4]的数据类型为:int32
npy_str:[b'1' b'2' b'3' b'4']数据类型为:|S11
npy_bool:[ True  True  True  True],数据类型:bool


In [ ]:
#转化:将浮点数字符串转化为整数不可行

import numpy as np

arr=np.array(["1.23","2.121","34.22"],dtype="U")


#转化:
arr_1=arr.astype(float)
print(arr_1)

arr_2=arr.astype(int)
arr_2

[ 1.23   2.121 34.22 ]


ValueError: invalid literal for int() with base 10: np.str_('1.23')

In [13]:
#还可以使用另一个数组的dtype属性

import numpy as np

#创建数组的另一种方法:np.arange()
arr_int=np.arange(10)
print(arr_int)

arr_float=np.array([1,2,3,4,5,6],dtype=np.float64)
print(arr_float)

#使用arr_float的dtype属性将arr_int转化为浮点数数据类型

arr=arr_int.astype(arr_float.dtype)
arr


[0 1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6.]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])