In [ ]:
"""
numpy可以读写磁盘上的文本数据和二进制格式数据:

numpy.save和numpy.load是读写磁盘数据的2个主要函数,
默认情况数组是以未压缩的二进制格式保存在.npy文件中的
"""

In [ ]:
import numpy as np
arr=np.arange(10)

#保存数组
np.save("D:/dataset/some_array.npy",arr)

In [ ]:
#读取数组
np.load("D:/dataset/some_array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#使用numpy.savez()可以将多个数组保存到一个未压缩的文件中,以数组关键字的形式传入即可

arr_1=np.arange(9).reshape((3,3))
arr_2=np.arange(12).reshape((3,4))

# 注意many_array.npz后缀为npz压缩文件
np.savez("D:/dataset/many_array.npz",a=arr_1,b=arr_2)

In [ ]:
#加载(load)压缩文件时,会得到类似字典的对象,访问内容使用关键字key

x=np.load("D:/dataset/many_array.npz")
print(x)

NpzFile 'D:/dataset/many_array.npz' with keys: a, b


In [ ]:
#使用钥匙key来读取压缩文件的数组
x["a"]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
x["b"]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
#将数组存入已压缩文件的方法:
np.savez_compressed("D:/dataset/many_array.npz",c=np.array([1,2,3]))

In [25]:
npz=np.load("D:/dataset/many_array.npz")
npz["c"]

array([1, 2, 3])