In [4]:
#矩阵乘法:
#dot函数既是numpy命名空间的函数也是数组方法
import numpy as np

arr1=np.arange(9).reshape((3,3))
arr2=np.arange(12).reshape((3,4))
print(f"{arr1}\n{arr2}")

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
#numpy命名空间函数
new=np.dot(arr1,arr2)
print(new)

[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]]


In [6]:
#或者使用数组方法
new2=arr1.dot(arr2)
print(new2)

[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]]


In [7]:
#或者使用符号@
arr1@arr2

array([[ 20,  23,  26,  29],
       [ 56,  68,  80,  92],
       [ 92, 113, 134, 155]])

In [11]:
#2维数组和一维数组(满足前列数等于后行数)矩阵点积运算将得到一个一维数组

x=np.arange(3)

y=np.arange(6).reshape((3,2))
print(f"{x}\n{y}")

x@y

[0 1 2]
[[0 1]
 [2 3]
 [4 5]]


array([10, 13])

In [ ]:
#numpy.linalg中有矩阵分解运算,以及求逆和,求行列式等方法,常用的numpy.linalg方法去官方文档查阅
from numpy.linalg import inv,qr
rng=np.random.default_rng(seed=12345)

X=rng.standard_normal((5,5))
print(X)
mat=X.T@X
print(mat)

[[-1.42382504  1.26372846 -0.87066174 -0.25917323 -0.07534331]
 [-0.74088465 -1.3677927   0.6488928   0.36105811 -1.95286306]
 [ 2.34740965  0.96849691 -0.75938718  0.90219827 -0.46695317]
 [-0.06068952  0.78884434 -1.25666813  0.57585751  1.39897899]
 [ 1.32229806 -0.29969852  0.90291934 -1.62158273 -0.15818926]]
[[ 9.83867527  1.04334204  0.24651754  0.04017965  0.16391486]
 [ 1.04334204  5.11794735 -3.98521413  0.99264687  3.27464142]
 [ 0.24651754 -3.98521413  4.15026075 -2.41299778 -2.74788646]
 [ 0.04017965  0.99264687 -2.41299778  3.97263789 -0.04472489]
 [ 0.16391486  3.27464142 -2.74788646 -0.04472489  6.01956209]]


In [16]:
inv(mat)

array([[ 0.15548538, -0.36723081, -0.52638547, -0.2300642 , -0.04646089],
       [-0.36723081,  2.54917814,  3.47827334,  1.48196722,  0.22206454],
       [-0.52638547,  3.47827334,  5.46389554,  2.46214396,  0.63467543],
       [-0.2300642 ,  1.48196722,  2.46214396,  1.38302896,  0.33430132],
       [-0.04646089,  0.22206454,  0.63467543,  0.33430132,  0.33879566]])

In [17]:
mat@inv(mat)

array([[ 1.00000000e+00, -8.32667268e-17,  1.24900090e-16,
         1.38777878e-17, -1.38777878e-17],
       [ 4.44089210e-16,  1.00000000e+00, -3.55271368e-15,
        -1.55431223e-15, -2.22044605e-16],
       [-2.49800181e-16,  8.88178420e-16,  1.00000000e+00,
        -6.66133815e-16,  3.33066907e-16],
       [-1.17093835e-16,  1.77462212e-15,  5.93275429e-16,
         1.00000000e+00,  2.20309881e-16],
       [ 3.88578059e-16,  6.66133815e-16, -2.22044605e-15,
        -1.33226763e-15,  1.00000000e+00]])