In [12]:
import numpy as np

arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr_3d[0]
print(arr_3d)

#写入副本
arr_3d_cp=arr_3d[0].copy()
print(arr_3d_cp)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [ ]:

#修改视图:
arr_3d[0]=6

#查看修改视图后的数组
arr_3d

array([[[ 6,  6,  6],
        [ 6,  6,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:

#使用副本,变回原来的数组
arr_3d[0]=arr_3d_cp
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#部分索引返回:

arr_3d[1,0]


array([7, 8, 9])