In [2]:
import numpy as np

arr_3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [5]:
#二维数组切片,取出一个二维数组

arr_2d=arr_3d[0]

#对其进行切片:
slice1=arr_2d[:2]
print(slice1)
##沿着y轴切说明切片是按着轴向选取元素的

#多个参数
slice2=arr_2d[:2,1:]
print(slice2,slice2.shape)
#可以看到先按照y轴方向切割前2行,再x轴切第2列和第三列
#shape大小为(2,2)是2*2的二维数组

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]] (2, 2)


In [ ]:
#选取第二行的前两列
slice3=arr_2d[1,:2]
print(slice3,slice3.shape)

#(2,)一维数组

[4 5] (2,)


In [8]:
#选择第三列的前两行

slice4=arr_2d[:2,2]
print(slice4,slice4.shape)

[3 6] (2,)


In [ ]:
#冒号本身意味着选取整个轴,因此可以只对高维轴进行切片
slice5=arr_2d[:2,2:]
print(slice5,slice5.shape)


"""
在NumPy中对二维数组进行切片时,是否降维取决于 
切片操作中是否在某个维度上使用了索引（单个值）而非切片（含冒号)

单个索引（无冒号）会导致降维,切片（含冒号）会保留维度
"""

[[3]
 [6]] (2, 1)


''

In [12]:
#当然对切片表达式赋值也会扩散到整个数组:

arr_3d[1,:2,1:]=0

print(arr_3d,arr_3d.shape)


[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10  0  0]
  [13  0  0]
  [16 17 18]]] (2, 3, 3)
