In [ ]:
import numpy as np

#使每一个名字对应一个数组
names=np.array(["bob","jack","link","link","bob","jack","bob"])

data=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12],[13,14]])

#创建布尔数组:

#数组的比较运算也是向量化的,会将""bob"扩散进数组进行逻辑运算,产生一个布尔数组
names=="bob"

array([ True, False, False, False,  True, False,  True])

In [ ]:
#布尔数组可以做布尔索引,是true的会选取按照轴向

data[names=="bob"]

array([[ 1,  2],
       [ 9, 10],
       [13, 14]])

In [3]:
#搭配单个索引降维
data[names=="bob",1]

array([ 2, 10, 14])

In [4]:
data[names=="bob",1:]

array([[ 2],
       [10],
       [14]])

In [ ]:
#要选取除了bob以外的数据可以使用!=或者~对条件求反
names!="bob"

array([False,  True,  True,  True, False,  True, False])

In [6]:
~(names=="bob")

array([False,  True,  True,  True, False,  True, False])

In [7]:
data[~(names=="bob")]

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [11, 12]])

In [ ]:
#从选取3个人选取2个名字进行数据组合可以使用|(或)和&(和)

#|满足其一即可,相当于把bob和link都扩散进去
target=(names=="bob")|(names=="link")
target

array([ True, False,  True,  True,  True, False,  True])

In [11]:
data[target]

array([[ 1,  2],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [13, 14]])

In [14]:

#注意bool索引也是索引可以用来干修改赋值的事情

#将数组内小于5的修改为5
data[data<5]=5
data

array([[ 5,  5],
       [ 5,  5],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])