In [3]:
#花式索引指用整数数组进行索引
import numpy as np

#创建一个数组
arr_1=np.empty((8,4))
for i in range(8):
    #取数组的每一行
    arr_1[i]=i

arr_1

#先创框架,再去赋值

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [4]:
#或者使用np.arange()reshape()快速创建多维数组

arr=np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [5]:
#使用索引数组索引:

arr_1[[1,2,4]]#数组里是索引


array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [4., 4., 4., 4.]])

In [6]:
#一次传入多个索引数组会返回一维数组

arr[[1,5,7,2],[0,3,1,2]]

#结果来看返回的是坐标为(1,0),(5,3)....的值组成的一维数组

array([ 4, 23, 29, 10])

In [ ]:
#如果我想要矩阵的二维切片数组可以使用这种方法:

arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [16]:
#以下为这种方式的解释:

print(arr[:,[0]])
print(arr[:,0])#说明索引数组作为索引使用不会降维


[[ 0]
 [ 4]
 [ 8]
 [12]
 [16]
 [20]
 [24]
 [28]]
[ 0  4  8 12 16 20 24 28]


In [17]:
arr[[1,5,7,2]]
arr[[1,5,7,2]][:,[0,3]]

array([[ 4,  7],
       [20, 23],
       [28, 31],
       [ 8, 11]])

In [18]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [ ]:
#注意花式索引和切片不一样,对结果赋值时,他总是将数据复制到新数组:

#切片:
arr = np.array([0, 1, 2, 3, 4])
s = arr[1:4]  # 视图
s[0] = 10     # 原数组变为 [0, 10, 2, 3, 4]

#花式索引:
fancy = arr[[1,3,4]]  # 副本
fancy[0] = 20         # 原数组仍为 [0, 10, 2, 3, 4]

#但是直接对原数组的花式索引赋值会修改原数组,因为没有创建副本
arr[[1, 3]] = 20  # 原数组变为 [0, 20, 2, 20, 4]