In [ ]:
#数组是可以进行运算的:

import numpy as np

arr_1=np.array([[1,2,3],[4,5,6]])

arr_2=np.array([[2,2,2],[3,3,3]])

#两个数组运算

#逐元素乘法*        区别矩阵乘法@
result1=arr_1*arr_2
print(result1)

result2=arr_1+arr_2
print(result2)

result3=arr_1/arr_2
result3



[[ 2  4  6]
 [12 15 18]]
[[3 4 5]
 [7 8 9]]


array([[0.5       , 1.        , 1.5       ],
       [1.33333333, 1.66666667, 2.        ]])

In [7]:
#数组与标量进行算数运算会将标量值传入数组的各个元素

1/arr_2

array([[0.5       , 0.5       , 0.5       ],
       [0.33333333, 0.33333333, 0.33333333]])

In [8]:
arr_1**3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [9]:
#形状相同的两个数组进行比较会产生布尔数组

arr_1>arr_2

array([[False, False,  True],
       [ True,  True,  True]])

In [ ]:
#不同大小的数组之间的运算称为广播,例如  arr_1**3 中标量3就广播到数组各个元素了