In [1]:
import numpy as np

#切以一维数组为例：
num=np.array([1,2,3,4,5,6,7,8])
#切片操作
print(f"num从索引0到索引3的切片：{num[0:3]}")
print(f"num从索引-3到索引-1的切片：{num[-3:-1]}")
print(f"从头切到尾{num[::1]}step为2{num[::2]}")
#默认step为1，即切片间隔为1
print(f"num从索引0到索引6,切片间隔为2的切片：{num[0:6:2]}")

#数据切片是原始数组的视图,数据不会被复制存副本
#取数组切片赋值,会自动更改原数组
num[0:4]=0
print(num)


num从索引0到索引3的切片：[1 2 3]
num从索引-3到索引-1的切片：[6 7]
从头切到尾[1 2 3 4 5 6 7 8]step为2[1 3 5 7]
num从索引0到索引6,切片间隔为2的切片：[1 3 5]
[0 0 0 0 5 6 7 8]


In [10]:
#切以二维数组为例：
#定义二维数组
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
#切片操作:arr[数组维度,切片索引]
print(f"arr的第一行:{arr[0]}")
print(f"arr的第二行:{arr[1]}")
print(f"对arr的第二行进行切片(从第二个元素开始切到末尾的元素){arr[1,1:4]}")
print(f"对arr的第一行切片从末尾切到首{arr[0,::-1]}")

arr的第一行:[1 2 3 4 5]
arr的第二行:[ 6  7  8  9 10]
对arr的第二行进行切片(从第二个元素开始切到末尾的元素)[7 8 9]
对arr的第一行切片从末尾切到首[5 4 3 2 1]


In [17]:
#2.切片语法 arr[行选择, 列选择]

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#0:2表示从第一行到第三行(不包含第三行),2表示第三列
print(arr[0:2, 2])


[8]


In [19]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

#取数组的1,2行,2到4列
print(arr[0:2, 1:4])   #这将返回一个二维数组


#等价于
#print(arr[:,1:4])


[[2 3 4]
 [7 8 9]]
