In [1]:
#复制和视图之间的区别:
#副本和数组视图之间的主要区别在于 副本是一个新数组，视图只是原始数组的视图。

#副本拥有数据对副本所做的任何更改都不会影响原始数组，并且对原始数组所做的任何更改都不会影响副本。

#视图不拥有数据,对视图所做的任何更改都将影响原始数组,并且对原始数组所做的任何更改都将影响视图。


In [ ]:
#副本:

import numpy as np
arr=np.array([1,2,3,4,5])

arr_copy=arr.copy()

#更改数组的内容:
arr[0]=42

print(arr)
print(arr_copy)

[42  2  3  4  5]
[1 2 3 4 5]


In [3]:
#创建一个视图，更改原始数组，并显示两个数组：
import numpy as np
arr=np.array([1,2,3,4,5,6])

arr_view=arr.view()
arr[0]=42

print(f"{arr}\n{arr_view}")


[42  2  3  4  5  6]
[42  2  3  4  5  6]


In [1]:
#对视图进行更改:
import numpy as np
arr=np.array([1,2,3,4,5,6])

#创建视图:
arr_view=arr.view()
#更改试图:
arr_view[0]=34

print(f"{arr}\n{arr_view}")

[34  2  3  4  5  6]
[34  2  3  4  5  6]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])

#视图:注意arr[1:4]是视图,所以赋值给变量slice也是视图,不要误认副本
slice=arr[1:4]


#检测slice是不是视图
print(slice.base)#[2 3 4]说明依赖原数组是视图
print(slice)

#更改试图
slice[0:2]=1
print(arr)

slice[:]=0
arr

[1 2 3 4 5 6]
[2 3 4]
[1 1 1 4 5 6]


array([1, 0, 0, 0, 5, 6])

In [6]:
#检查 Array 是否拥有其数据
#副本拥有数据，而视图不拥有数据,检查方式是arr.base检查是否依赖原数据,
#副本是独立数据,所以返回None,视图是依赖原数据的所以返回原数组

import numpy as np
arr=np.array([1,2,3,4,5,6])


#创建副本
arr_copy=arr.copy()

#创建视图:
arr_view=arr.view()

#检查视图是否拥有数据
print(arr_copy.base)
print(arr_view.base)


None
[1 2 3 4 5 6]


In [17]:
#如果想要视图的副本可以复制copy()
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr_cp=arr[:].copy()

print(arr_cp.base)

None
