In [1]:
#重塑数组

#重塑意味着更改数组的形状。

#数组的形状是每个维度中的元素数。

#通过重塑，我们可以添加或删除维度或更改每个维度中的元素数量

In [ ]:
#一.从 1-D 到 2-D 的修整

#例子:将以下具有 12 个元素的 1-D 数组转换为 2-D 数组,
#最外层的维度将有 4 个数组，每个数组有 3 个元素：

#方法:arr.reshape()
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

re_arr=arr.reshape(4,3)
print(f"re_arr:\n{re_arr}")



re_arr:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#二.从 1-D 重塑为 3-D
#将以下具有 12 个元素的一维数组转换为三维数组。
#最外层的维度(层)将有2个数组，每个数组包含3个数组，每个数组包含2个元素：

import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])


re_arr=arr.reshape(2,3,2)
print(f"re_arr:\n{re_arr}\n类型:{re_arr.base}")
#使用base方法,返回了数组说明重塑的数组是视图,而不是副本.

re_arr:
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
类型:[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#三.扁平化数组(Flattening array)是指将多维数组转换为 1D 数组

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

#扁平化数组:
f_arr=arr.reshape(6)
f_arr=arr.reshape(-1)
print(f"f_arr:\n{f_arr}\n类型:\n{f_arr.base}")


f_arr:
[1 2 3 4 5 6]
类型:
[[1 2 3]
 [4 5 6]]


In [ ]:
#四.未知维度:
#在NumPy中，使用 -1 作为 reshape的维度参数表示“自动计算该维度的大小”，
#使得新数组的总元素数与原始数组一致.这是NumPy提供的一种便捷方式,避免手动计算某个维度的具体值。

#将具有 1 个元素的 8D 数组转换为具有 3x2 元素的 2D 数组：

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6,])
arr.reshape((3,-1))


array([[1, 2],
       [3, 4],
       [5, 6]])