In [37]:
import numpy as np

arr=np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [43]:
#转置:arr.T方法,可以进行轴对换,x与y轴交换

arr_new=arr.T
print(arr_new)#可以看到y轴的数据到x轴向了,同理x轴


#检查原数组是否发生改变:
print(arr)


[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [13]:
#numpy.dot(),在进行矩阵运算时可能用到np.dot()计算矩阵内积:
import numpy as np
arr=np.arange(12).reshape(4,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
#4*3和3*4形成4*4的数组
new_arr=np.dot(arr,arr.T)
print(new_arr)

print(arr)
#arr不变说明两数组矩阵内积不会改变原来的数组内容


#3*4和4*3形成3*3的数组
new_arr2=np.dot(arr.T,arr)
print(new_arr2)
print(arr)

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[126 144 162]
 [144 166 188]
 [162 188 214]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
#另一种做矩阵乘法的是@
#new_arr2=np.dot(arr.T,arr)等价于arr@arr.T

print(arr@arr.T)
print(arr.T@arr)
arr

#在矩阵乘法中，arr 和 arr.T 是独立的，对转置矩阵的使用不会改变原数组 arr 的值

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[126 144 162]
 [144 166 188]
 [162 188 214]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
#arr.T返回的是视图,所以使用arr.T会修改原数组
import numpy as np
# 创建一个二维数组
arr = np.array([[1, 2], [3, 4]])
print("Original arr:")
print(arr)
# [[1 2]
#  [3 4]]

# 获取转置视图
arr_transposed = arr.T
print("Transposed arr:")
print(arr_transposed)
print(arr)
# [[1 3]
#  [2 4]]

#[[1 3]
# [2 4]]

# 修改转置视图中的元素
arr_transposed[0, 0] = 100
print("Modified transposed arr:")
print(arr_transposed)
# [[100   3]
#  [  2   4]]

# 检查原数组是否改变
print("Original arr after modification:")
print(arr)
# [[100   2]
#  [  3   4]]

Original arr:
[[1 2]
 [3 4]]
Transposed arr:
[[1 3]
 [2 4]]
[[1 2]
 [3 4]]
Modified transposed arr:
[[100   3]
 [  2   4]]
Original arr after modification:
[[100   2]
 [  3   4]]


In [45]:
#arr.swapaxes()接受一对轴编号,对换标记的轴以重排数据
arr = np.array([[1, 2, 3], [4, 5, 6]])  # 形状 (2, 3)
swapped=arr.swapaxes(1,0)            # 形状变为 (3, 2)
print(swapped)

print(arr)
#只是简单地调用swapaxes并没有对返回的数组进行修改,原数组不会改变。
#因为 swapaxes 的调用本身不会改变原数组，而只是返回一个新的视图

swapped[:2,:]=0

#检查视图:
print(swapped)

#检查原数组
print(arr)


[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]
[[0 0]
 [0 0]
 [3 6]]
[[0 0 3]
 [0 0 6]]
