In [2]:
#通用函数(ufunc)是一种对ndarray中的数据执行 元素级运算 的函数

import numpy  as np

arr=np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [3]:
#对其使用  一元通用函数(接受一个数组)  ,进行简单元素转换 np.sqrt() 和np.exp()

arr_1=np.sqrt(arr)
print(arr_1)

arr_2=np.exp(arr)
print(arr_2)

#检查原数组
print(arr)

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739]]
[[1.00000000e+00 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04]
 [1.62754791e+05 4.42413392e+05 1.20260428e+06]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [56]:
#二元ufunc(接受2个数组)

#先配置一个生产器,提供随机数据使用
rng=np.random.default_rng(seed=12345)

x=rng.standard_normal(8)
print(x)

y=rng.standard_normal(8)
print(y)


#使用np.maximum(x.y)二元ufunc比较x与y对应元素的大小,取最大值.
arr_3=np.maximum(x,y)

print(arr_3)


[-1.42382504  1.26372846 -0.87066174 -0.25917323 -0.07534331 -0.74088465
 -1.3677927   0.6488928 ]
[ 0.36105811 -1.95286306  2.34740965  0.96849691 -0.75938718  0.90219827
 -0.46695317 -0.06068952]
[ 0.36105811  1.26372846  2.34740965  0.96849691 -0.07534331  0.90219827
 -0.46695317  0.6488928 ]


In [62]:
#ufunc也可返回2个数组

#返回整数和小数np.modf(arr)
rng=np.random.default_rng(seed=12345)

arr=rng.standard_normal(7)*7
print(arr)

reminder,wholepart=np.modf(arr)
print(reminder,wholepart)


[-9.96677526  8.84609921 -6.09463217 -1.81421264 -0.52740315 -5.18619256
 -9.57454891]
[-0.96677526  0.84609921 -0.09463217 -0.81421264 -0.52740315 -0.18619256
 -0.57454891] [-9.  8. -6. -1. -0. -5. -9.]


In [ ]:
#ufunc具体还有很多可以查看官网文档获取