In [21]:
"""
numpy.where函数是三元表达式 x if condition else y 的向量化版本

"""
import numpy as np

cond=np.array([True,True,False,True,False])
arr_1=np.array([1,2,3,4,5])
arr_2=np.array([6,7,8,9,10])

#如果根据cond数组选择arr1和arr2中的数据,当cond中的值为true时选arr1

#使用列表推导式法:
list_1=[(x if bool==True else y) for x,y,bool in zip(arr_1,arr_2,cond) ]
list_1

[np.int64(1), np.int64(2), np.int64(8), np.int64(4), np.int64(10)]

In [ ]:
#用np.where(条件数组,x,y)方法效率高又简洁

arr=np.where(cond,arr_1,arr_2)
arr

array([ 1,  2,  8,  4, 10])

In [25]:
#where里面的第二第三参数不局限于数组可以是一个或二个标量值,

#比如将true对应的数据替换为99
arra=np.where(cond,99,arr_2)
arra

array([99, 99,  8, 99, 10])

In [26]:
#将2个变量全变为标量:True的改为1false的改为0
arr_1=np.array([1,2,3,4,5])
rng=np.random.default_rng(seed=12345)

arr_a=rng.standard_normal((4,4))
print(arr_a)

arr_b=np.where(arr_1>3,1,0)
arr_b

[[-1.42382504  1.26372846 -0.87066174 -0.25917323]
 [-0.07534331 -0.74088465 -1.3677927   0.6488928 ]
 [ 0.36105811 -1.95286306  2.34740965  0.96849691]
 [-0.75938718  0.90219827 -0.46695317 -0.06068952]]


array([0, 0, 0, 1, 1])

In [ ]:
#注意np.where(cond,x,y)
#x数组和y数组的元素类型必须一致,不能字符串和数字存在一起