In [2]:
"""
sum,mean 等聚合运算既可以用作数组的实例方法调用,也可以使用顶层的numpy函数
比如numpy.sum将要聚合的数组 作为第一个参数

"""
import numpy as np
rng=np.random.default_rng(seed=12345)

#生产一个正态分布随机数据,然后做类据统计
arr=rng.standard_normal((5,4))
arr

array([[-1.42382504,  1.26372846, -0.87066174, -0.25917323],
       [-0.07534331, -0.74088465, -1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306,  2.34740965,  0.96849691],
       [-0.75938718,  0.90219827, -0.46695317, -0.06068952],
       [ 0.78884434, -1.25666813,  0.57585751,  1.39897899]])

In [3]:
arr.sum()

np.float64(0.021223322497782027)

In [4]:
arr.mean()

np.float64(0.0010611661248891013)

In [5]:
np.mean(arr)

np.float64(0.0010611661248891013)

In [6]:
"""
mean和sum函数可以接受一个参数axis用于计算该轴向上的统计值,最终结果是低一维的数组

轴(axis)的定义:
对于二维数组（矩阵）：

axis=0:表示沿着行的方向（垂直向下），即对同一列的元素进行操作。

axis=1:表示沿着列的方向（水平向右），即对同一行的元素进行操作。
"""
#计算的每一列的平均值
arr.mean(0)
#计算的每一行的平均值
arr.mean(1)

array([-0.32248289, -0.38378196,  0.4310254 , -0.0962079 ,  0.37675318])

In [10]:
#计算每一行的和
arr.sum(1)
#计算每一列的和
arr.sum(0)

array([-1.10865307, -1.78448912,  0.21785956,  2.69650595])

In [8]:
"""
累积函数:cumsum,不聚合,与sum(聚合为单个值)不同,返回同样大小的数组.
中间结果：每一步的累加结果都会被保留，最终输出所有中间值组成的数组
"""
#cumsum（累计求和）方法会生成一个数组，其中每个元素是原数组从起始位置到当前位置所有元素的累加和
import numpy as np
arr_1=np.array([1,1,1,1,1,1])

x=arr_1.cumsum()
print(x)
#每个位置的值是前面所有元素（包括自身）的累加和

[1 2 3 4 5 6]


In [11]:
#多维数组与轴:对于多维数组，cumsum 可以沿指定轴（axis）进行累计操作：

arr_2=np.array([[1,2,3],[4,5,6]])

#求行的累加数组
y=arr_2.cumsum(1)
print(y)

#求列的累加数组
z=arr_2.cumsum(0)
print(z)


[[ 1  3  6]
 [ 4  9 15]]
[[1 2 3]
 [5 7 9]]


In [ ]:
"""
基本的数组统计方法
    方法            功能              轴参数
np.sum()	计算数组元素的总和	支持
np.mean()	计算数组的平均值	支持
np.max()	计算数组中的最大值	支持
np.min()	计算数组中的最小值	支持
np.median()	计算数组的中位数	支持
np.std()	计算数组的标准差	支持
np.var()	计算数组的方差	支持
np.percentile()	计算数组的百分位数	支持

"""