In [12]:
#类似于python内置的列表类型,numpy数组也可以通过sort方法排序
import numpy as np
rng=np.random.default_rng(seed=12345)

arr=rng.standard_normal((4,4))
arr

array([[-1.42382504,  1.26372846, -0.87066174, -0.25917323],
       [-0.07534331, -0.74088465, -1.3677927 ,  0.6488928 ],
       [ 0.36105811, -1.95286306,  2.34740965,  0.96849691],
       [-0.75938718,  0.90219827, -0.46695317, -0.06068952]])

In [ ]:
#使用sort方法排序,也可使用轴参数对行和列排序
"""
问题的原因：
ndarray.sort() 方法会直接排序原始数组，并且返回值是 None,而不是排序后的数组。
因此 arr1 的值为 None,所以没有输出。
正确的用法：
如果你希望得到排序后的数组（不对原始数组进行修改），应该使用 np.sort() 函数。
否则，如果你希望就地排序原始数组，可以使用 ndarray.sort() 方法
"""
#对行排序
arr1=arr.sort(1)
arr1

In [ ]:
#对每一列排序
arr.sort(0)
arr

array([[-1.42382504, -1.95286306, -1.3677927 , -0.25917323],
       [-0.75938718, -0.74088465, -0.87066174, -0.06068952],
       [-0.07534331,  0.90219827, -0.46695317,  0.6488928 ],
       [ 0.36105811,  1.26372846,  2.34740965,  0.96849691]])

In [14]:
#对每一行排序
arr.sort(1)
arr

array([[-1.95286306, -1.42382504, -1.3677927 , -0.25917323],
       [-0.87066174, -0.75938718, -0.74088465, -0.06068952],
       [-0.46695317, -0.07534331,  0.6488928 ,  0.90219827],
       [ 0.36105811,  0.96849691,  1.26372846,  2.34740965]])

In [ ]:
#np.sort()函数与上面的数组对象方法的区别是
#np.sort()函数返回的是副本,而非视图

arr_1=np.array([1,-1,-4,3,9])

arr_1_new=np.sort(arr_1)
print(arr_1_new)
print(arr_1)#原数组没有被修改

[-4 -1  1  3  9]
[ 1 -1 -4  3  9]


In [26]:
rng=np.random.default_rng(seed=12345)
arr_2=rng.standard_normal((4,4))
print(arr_2)

arr_2_new=np.sort(arr_2,axis=0)
arr_2_new

[[-1.42382504  1.26372846 -0.87066174 -0.25917323]
 [-0.07534331 -0.74088465 -1.3677927   0.6488928 ]
 [ 0.36105811 -1.95286306  2.34740965  0.96849691]
 [-0.75938718  0.90219827 -0.46695317 -0.06068952]]


array([[-1.42382504, -1.95286306, -1.3677927 , -0.25917323],
       [-0.75938718, -0.74088465, -0.87066174, -0.06068952],
       [-0.07534331,  0.90219827, -0.46695317,  0.6488928 ],
       [ 0.36105811,  1.26372846,  2.34740965,  0.96849691]])

In [ ]:
"""
np.sort() 默认情况下会对二维数组按行排序（axis=1）。
如果需要按列排序，可以设置 axis=0。
如果需要将整个数组展平后再排序，可以设置 axis=None。
"""